#!/usr/bin/env python3
"""
Read the per-campaign players roster (campaigns/<campaign>/players.yml).

Hand-authored alongside each character's Jekyll page
(campaigns/<campaign>/_pages/characters/<slug>.md) - not generated by any
skill. This maps each real-world player to the character slug(s) they run,
which `dm-livesession` needs to know who it's narrating for (a solo
player-mode session may run several PCs) and to answer DM co-pilot PC
lookups.

Read-only: `dm-livesession` never creates or edits `players.yml` or the
character pages - both are treated as campaign setup, same as
`party.yml`'s composition.

Parsing is hand-rolled for this exact shape (not a general YAML library),
duplicating party_state.py's precedent of a small skill-local parser
rather than importing a shared one:

  players:
    - name: Chuck
      slug: chuck
      characters:
        - aiden-oathkeeper
        - dravroth-oathbreaker

CLI usage:
  python3 players_state.py read --campaign my-campaign

Output (found): {"players": [{"name": "Chuck", "slug": "chuck",
  "characters": ["aiden-oathkeeper", ...]}, ...]}
Output (not found): {"found": false} - not an error; a campaign may not
  have a players.yml yet (e.g. a `dm`-mode campaign with no solo PCs of
  its own to track).
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def find_repo_root(start: Path) -> Path:
    current = start.resolve()
    for candidate in [current, *current.parents]:
        if (candidate / ".git").exists():
            return candidate
    raise FileNotFoundError(f"No .git directory found above {start}")


def _players_path(repo_root: Path, campaign: str) -> Path:
    return repo_root / "campaigns" / campaign / "players.yml"


def read_players_state(repo_root: Path, campaign: str) -> dict | None:
    path = _players_path(repo_root, campaign)
    if not path.exists():
        return None

    players: list[dict[str, object]] = []
    current_player: dict[str, object] | None = None
    in_characters = False
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.rstrip()
        stripped = line.strip()
        if not stripped or stripped == "players:":
            continue
        if stripped.startswith("- name:"):
            current_player = {"name": stripped.split(":", 1)[1].strip(), "characters": []}
            players.append(current_player)
            in_characters = False
        elif current_player is None:
            continue
        elif stripped.startswith("slug:"):
            current_player["slug"] = stripped.split(":", 1)[1].strip()
            in_characters = False
        elif stripped == "characters:":
            in_characters = True
        elif in_characters and stripped.startswith("- "):
            current_player["characters"].append(stripped[2:].strip())
        else:
            in_characters = False

    if not players:
        return None
    return {"players": players}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    read_parser = subparsers.add_parser("read")
    read_parser.add_argument("--campaign", required=True)

    args = parser.parse_args()
    repo_root = find_repo_root(Path.cwd())

    if args.command == "read":
        state = read_players_state(repo_root, args.campaign)
        print(json.dumps(state if state is not None else {"found": False}))
        return 0

    return 1


if __name__ == "__main__":
    raise SystemExit(main())
