#!/usr/bin/env python3
"""
Write a Jekyll-ready draft file for a generated skill (encounter, location,
monster, magic-item, ...).

Lives at the repo root (not nested under ai/skills/) so it can be the single
source of this logic for both the skill scripts and, eventually, the FastAPI
service - see services/llm_api/src/llm_api/services/drafts.py::write_draft(),
which currently duplicates this format and should import from here instead
once that alignment work happens (out of scope for this plan). The
deterministic id formula matches services/llm_api/src/llm_api/services/ids.py
exactly, so ids stay consistent whether a draft was generated by a skill or
the API.

Skill scripts that need this module add the repo root's `shared/` directory
to sys.path (walk up from the script's own path to find `.git`, then
`sys.path.insert(0, str(repo_root / "shared"))`) rather than importing across
the ai/skills <-> services/llm_api boundary in either direction.

CLI usage:
  echo '{"kind": "encounter", "slug": "goblin-ambush", "title": "Goblin Ambush",
         "frontmatter": {"layout": "encounter", ...}, "body": "..."}' \
      | python3 write_draft.py

  Campaign is auto-resolved from .active-campaign unless "campaign" is given
  in the input JSON.

Output (stdout): {"path": "campaigns/<campaign>/_drafts/<kind>/<slug>.md", "id": "<uuid>"}
On error: {"error": {"code": "...", "message": "..."}}, exit code 1.
"""
from __future__ import annotations

import json
import sys
import uuid
from pathlib import Path
from typing import Any

# Same namespace as services/llm_api/src/llm_api/constants.py::UUID_NAMESPACE.
# Must never change: it's the id-stability contract between the API and skill paths.
UUID_NAMESPACE = uuid.UUID("c9b4f65f-2d5a-4e62-9e04-8b6ea6c60b41")


class DraftWriteError(Exception):
    def __init__(self, code: str, message: str):
        super().__init__(message)
        self.code = code
        self.message = message


def find_repo_root(start: Path) -> Path:
    """Walk upward from `start` until a directory containing `.git` is found."""
    current = start.resolve()
    for candidate in [current, *current.parents]:
        if (candidate / ".git").exists():
            return candidate
    raise DraftWriteError("repo_root_not_found", f"No .git directory found above {start}")


def get_active_campaign(repo_root: Path) -> str:
    active_path = repo_root / ".active-campaign"
    if not active_path.exists():
        raise DraftWriteError(
            "no_active_campaign", "No active campaign. Run scripts/use-campaign first."
        )
    campaign = active_path.read_text(encoding="utf-8").strip()
    if not campaign:
        raise DraftWriteError(
            "no_active_campaign", "Active campaign file is empty. Re-run scripts/use-campaign."
        )
    return campaign


def compute_draft_id(*, kind: str, campaign: str, slug: str) -> uuid.UUID:
    name = f"{kind}:{campaign}:{slug}"
    return uuid.uuid5(UUID_NAMESPACE, name)


def _yaml_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if value is None:
        return '""'
    text = str(value)
    if text == "" or any(ch in text for ch in [":", "#", "\n"]) or text != text.strip():
        return json.dumps(text)
    return text


def render_frontmatter(frontmatter: dict[str, Any]) -> str:
    """Render a flat dict (str/int/bool/list[str] values) as YAML front-matter.

    Deliberately minimal (not a general YAML emitter) - covers exactly the
    shapes the generator skills need: strings, ints, bools, and lists of
    strings.
    """
    lines: list[str] = []
    for key, value in frontmatter.items():
        if isinstance(value, list):
            if not value:
                lines.append(f"{key}: []")
            else:
                lines.append(f"{key}:")
                for item in value:
                    lines.append(f"  - {_yaml_scalar(item)}")
        else:
            lines.append(f"{key}: {_yaml_scalar(value)}")
    return "\n".join(lines) + "\n"


def write_draft(
    *,
    repo_root: Path,
    kind: str,
    campaign: str,
    slug: str,
    title: str,
    frontmatter: dict[str, Any],
    body: str,
) -> Path:
    drafts_dir = repo_root / "campaigns" / campaign / "_drafts" / kind
    try:
        drafts_dir.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise DraftWriteError("draft_write_failed", f"Failed to create drafts directory: {exc}")

    path = drafts_dir / f"{slug}.md"
    content = (
        "---\n"
        f"{render_frontmatter(frontmatter)}"
        "---\n\n"
        f"# {title}\n\n"
        f"{body.strip()}\n"
    )
    try:
        path.write_text(content, encoding="utf-8")
    except OSError as exc:
        raise DraftWriteError("draft_write_failed", f"Failed to write draft: {exc}")
    return path


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except json.JSONDecodeError as exc:
        print(json.dumps({"error": {"code": "invalid_input", "message": str(exc)}}))
        return 1

    try:
        repo_root = find_repo_root(Path.cwd())
        campaign = payload.get("campaign") or get_active_campaign(repo_root)
        kind = payload["kind"]
        slug = payload["slug"]
        title = payload["title"]
        frontmatter = payload["frontmatter"]
        body = payload["body"]

        draft_id = compute_draft_id(kind=kind, campaign=campaign, slug=slug)
        frontmatter = {**frontmatter, "id": str(draft_id), "slug": slug}
        path = write_draft(
            repo_root=repo_root,
            kind=kind,
            campaign=campaign,
            slug=slug,
            title=title,
            frontmatter=frontmatter,
            body=body,
        )
    except DraftWriteError as exc:
        print(json.dumps({"error": {"code": exc.code, "message": exc.message}}))
        return 1
    except KeyError as exc:
        print(json.dumps({"error": {"code": "invalid_input", "message": f"Missing field: {exc}"}}))
        return 1

    print(json.dumps({"path": str(path.relative_to(repo_root)), "id": str(draft_id)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
